# Generated by Django 3.2.4 on 2021-06-30 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_cart_cartitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='updated',
            new_name='deleted_at',
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together=set(),
        ),
    ]
