# Generated by Django 3.2.4 on 2021-07-03 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_billingprofile_stripe_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
